### succesfull login

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"test@test.fi",
    "password":"1234"
}

### wrong credential login

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"test@test.fi",
    "password":"12"
}
