### succesfull login

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password":"adminn"
}

### wrong credential login

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"test@test.fi",
    "password":"12"
}
