### Update users subscription
PUT http://localhost:3000/api/v1/newsletter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsImZpcnN0TmFtZSI6InRlc3RpdWtrbyIsImxhc3ROYW1lIjoiUGVydHRpIiwiZW1haWwiOiJzbXNAc21zLmZpIiwicGhvbmUiOiIwNDA1MjIyMTIzIiwiYWRkcmVzcyI6InNpaXBwYWt1amEiLCJjaXR5IjoiSGVsc2lua2kiLCJwb3N0YWxDb2RlIjoiMTIzNDUiLCJ0eXBlIjoidXNlciIsImlhdCI6MTc0NTkzNTA4MywiZXhwIjoxNzQ2MDIxNDgzfQ.KrWMJlgCs5M4UrHgSXVNTrjM625idzTKP0Qn6xQi67U
Content-Type: application/json

### Add guest subscriber
POST http://localhost:3000/api/v1/newsletter
Content-Type: application/json

{
  "email": "testiemaili@mauku.fi"
}

### Add newsletter (needs to be an admin account!)
POST http://localhost:3000/api/v1/newsletter/modify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImZpcnN0TmFtZSI6ImFkbWluaW4gZXR1bmltaSIsImxhc3ROYW1lIjoiYWRtaW5pbiBzdWt1bmltaSIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGhvbmUiOiIxMjM0NTY3ODkiLCJhZGRyZXNzIjoiYWRtaW5pbiBvc29pdGUiLCJjaXR5IjoiYWRtaW5pbiBrYXVwdW5raSIsInBvc3RhbENvZGUiOiJhZG1pbmluIHBvc3RpbnVtZXJvIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNzQ1OTM5OTc5LCJleHAiOjE3NDYwMjYzNzl9.W4iOas4bMisUw-OZhJuM9gNy4ut5ADDf0l9nOyzURWA
Content-Type: application/json

{
  "subject": "Kreisimpi tarjous!!!",
  "content": "Nyt kaikki paksit -10%!"
}

### Get newsletters (needs to be an admin account!)
GET http://localhost:3000/api/v1/newsletter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImZpcnN0TmFtZSI6ImFkbWluaW4gZXR1bmltaSIsImxhc3ROYW1lIjoiYWRtaW5pbiBzdWt1bmltaSIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGhvbmUiOiIxMjM0NTY3ODkiLCJhZGRyZXNzIjoiYWRtaW5pbiBvc29pdGUiLCJjaXR5IjoiYWRtaW5pbiBrYXVwdW5raSIsInBvc3RhbENvZGUiOiJhZG1pbmluIHBvc3RpbnVtZXJvIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNzQ1OTM5OTc5LCJleHAiOjE3NDYwMjYzNzl9.W4iOas4bMisUw-OZhJuM9gNy4ut5ADDf0l9nOyzURWA

### Delete newsletter by id (needs to be an admin account!)
DELETE http://localhost:3000/api/v1/newsletter/modify/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImZpcnN0TmFtZSI6ImFkbWluaW4gZXR1bmltaSIsImxhc3ROYW1lIjoiYWRtaW5pbiBzdWt1bmltaSIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGhvbmUiOiIxMjM0NTY3ODkiLCJhZGRyZXNzIjoiYWRtaW5pbiBvc29pdGUiLCJjaXR5IjoiYWRtaW5pbiBrYXVwdW5raSIsInBvc3RhbENvZGUiOiJhZG1pbmluIHBvc3RpbnVtZXJvIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNzQ1OTM5OTc5LCJleHAiOjE3NDYwMjYzNzl9.W4iOas4bMisUw-OZhJuM9gNy4ut5ADDf0l9nOyzURWA

### Get all subscribers (needs to be an admin account!)
GET http://localhost:3000/api/v1/newsletter/subscribers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImZpcnN0TmFtZSI6ImFkbWluaW4gZXR1bmltaSIsImxhc3ROYW1lIjoiYWRtaW5pbiBzdWt1bmltaSIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicGhvbmUiOiIxMjM0NTY3ODkiLCJhZGRyZXNzIjoiYWRtaW5pbiBvc29pdGUiLCJjaXR5IjoiYWRtaW5pbiBrYXVwdW5raSIsInBvc3RhbENvZGUiOiJhZG1pbmluIHBvc3RpbnVtZXJvIiwidHlwZSI6ImFkbWluIiwiaWF0IjoxNzQ1OTM5OTc5LCJleHAiOjE3NDYwMjYzNzl9.W4iOas4bMisUw-OZhJuM9gNy4ut5ADDf0l9nOyzURWA

