### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "first_name": "testiukko",
  "last_name": "Pertti",
  "email": "sms@sms.fi",
  "password": "salasana",
  "phone": "0405222123",
  "address": "siippakuja",
  "city": "Helsinki",
  "postal_code": "12345"
}

### Create a new user with switched address
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "address": "siippakuja",
  "first_name": "asd",
  "last_name": "asd",
  "email": "asdddddd@testi.ee",
  "password": "1234",
  "phone": "0405222123",
  "city": "Helsinki",
  "postal_code": "12345"
}

### Check email
GET http://localhost:3000/api/v1/users/available/hehe@gmail.com

### Create an admin user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "address": "adminin katu",
  "first_name": "adminin nimi",
  "last_name": "adminin sukunimi",
  "email": "admin@admin.com",
  "password": "adminn",
  "phone": "0405222123",
  "city": "Helsinki",
  "postal_code": "12345",
  "type": "admin"
}

