### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "first_name": "sms",
  "last_name": "Pertti",
  "email": "test@test.fi",
  "password": "1234",
  "phone": "0405222123",
  "address": "siippakuja",
  "city": "Helsinki",
  "postal_code": "12345",
  "type": "user"
}

### Create a new user with switched address
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "address": "siippakuja",
  "first_name": "asd",
  "last_name": "asd",
  "email": "asdddddd@testi.ee",
  "password": "1234",
  "phone": "0405222123",
  "city": "Helsinki",
  "postal_code": "12345",
  "type": "user"
}

