### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "first_name": "encryptTest",
  "last_name": "Pertti",
  "email": "testi@testi.ee",
  "password": "1234",
  "phone": "0405222123",
  "address": "siippakuja",
  "city": "Helsinki",
  "postal_code": "12345",
  "type": "user"
}
